/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as IndexImport } from './routes/index'
import { Route as PokimanIdImport } from './routes/pokiman/$id'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PokimanIdRoute = PokimanIdImport.update({
  path: '/pokiman/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/pokiman/$id': {
      id: '/pokiman/$id'
      path: '/pokiman/$id'
      fullPath: '/pokiman/$id'
      preLoaderRoute: typeof PokimanIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/pokiman/$id': typeof PokimanIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/pokiman/$id': typeof PokimanIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/pokiman/$id': typeof PokimanIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/register' | '/pokiman/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/register' | '/pokiman/$id'
  id: '__root__' | '/' | '/register' | '/pokiman/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  PokimanIdRoute: typeof PokimanIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  PokimanIdRoute: PokimanIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/register",
        "/pokiman/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/pokiman/$id": {
      "filePath": "pokiman/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
